name: 'Send to Components Action'
on:
  push:
    branches:
      - 'main'
      - 'master'
    paths:
      - 'components-info/*.json'
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - 'main'
      - 'master'
    paths:
      - 'components-info/*.json'
jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - uses : actions/checkout@v3
      - name: Workflow
        uses: heroku/components-action@main
        with:
             COMPONENTS_GHA_APP_ID: ${{ secrets.COMPONENTS_GHA_APP_ID}}
             COMPONENTS_GHA_APP_PRIVATE_KEY: ${{ secrets.COMPONENTS_GHA_APP_PRIVATE_KEY}}
             COMPONENTS_GHA_JSON_TOKEN: ${{ secrets.COMPONENTS_GHA_JSON_TOKEN}}
